"""added stacks fields to user

Revision ID: 2f488917e020
Revises: 5b48b9242e1c
Create Date: 2024-09-23 17:27:45.303982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f488917e020'
down_revision: Union[str, None] = '5b48b9242e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prevTxID', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('stx_address_testnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('stx_address_mainnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('btc_address_mainnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('btc_address_testnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'btc_address_testnet')
    op.drop_column('users', 'btc_address_mainnet')
    op.drop_column('users', 'stx_address_mainnet')
    op.drop_column('users', 'stx_address_testnet')
    op.drop_column('users', 'prevTxID')
    # ### end Alembic commands ###