"""users model

Revision ID: 349dfa8dd762
Revises: 8794d2e096c6
Create Date: 2024-09-23 22:43:15.971981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '349dfa8dd762'
down_revision: Union[str, None] = '8794d2e096c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###