"""added password hash to user

Revision ID: aa96d403bfe6
Revises: fa99a673f634
Create Date: 2024-09-24 14:43:00.961688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa96d403bfe6'
down_revision: Union[str, None] = 'fa99a673f634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['author_user_id'], ['uuid'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###