"""added categories to blog, short bio and pronouns to user

Revision ID: d94250336b1a
Revises: aa96d403bfe6
Create Date: 2024-09-26 10:55:17.629196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd94250336b1a'
down_revision: Union[str, None] = 'aa96d403bfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('pronouns', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'pronouns')
    op.drop_column('blogs', 'categories')
    # ### end Alembic commands ###