"""made the stacks fields unique

Revision ID: fa99a673f634
Revises: 349dfa8dd762
Create Date: 2024-09-24 00:15:37.426946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa99a673f634'
down_revision: Union[str, None] = '349dfa8dd762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['stx_address_testnet'])
    op.create_unique_constraint(None, 'users', ['stx_address_mainnet'])
    op.create_unique_constraint(None, 'users', ['btc_address_mainnet'])
    op.create_unique_constraint(None, 'users', ['btc_address_testnet'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###